services:
  ros-pca9685-ros2-control:
    image: ghcr.io/rosblox/ros-pca9685-ros2-control:humble
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    network_mode: "host"
    ipc: host
    pid: host
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    volumes:
      - ./pca9685_ros2_control/mixed_controller.yaml:/colcon_ws/install/pca9685_ros2_control_example/share/pca9685_ros2_control_example/config/mixed_controller.yaml    
      - ./pca9685_ros2_control/robot_description:/colcon_ws/install/pca9685_ros2_control_example/share/pca9685_ros2_control_example/urdf
      - ./pca9685_ros2_control/ros2_control_bringup.launch.py:/colcon_ws/install/pca9685_ros2_control_example/share/pca9685_ros2_control_example/launch/mixed_example.launch.py
    environment:
      - UID=${HOST_UID}
      - ROS_DOMAIN_ID
    command: su - ros --whitelist-environment=ROS_DOMAIN_ID /run.sh



